global:
  scrape_interval: 15s  # Intervalo global de scrapeo para todos los jobs.
  evaluation_interval: 15s  # Intervalo global para evaluar las reglas.

scrape_configs:
  # Scrape config para cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Cambia esto por la IP y puerto donde cAdvisor está corriendo.

  # Scrape config para Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape config para Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']      

  # - job_name: 'docker'
  #   static_configs:
  #     #- targets: ['host.docker.internal:9323']
  #     - targets: ['localhost:9323']

rule_files:
  - '/etc/prometheus/recording_rules.yml'
  - '/etc/prometheus/alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'  # Dirección donde Alertmanager está corriendo (puede ser diferente según tu configuración).

